import type { NextPage } from 'next';
import { signIn, useSession } from 'next-auth/react';
import Head from 'next/head';
import { useState } from 'react';
import Button from '~/components/Button';
import Card from '~/components/Card';

type TechnologyCardProps = {
  name: string;
  description: string;
  documentation: string;
};

const Home: NextPage = () => {
  const session = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <Button
          runOnClick={() => console.log('Bruh')}
          text={'Bruh'}
          // useArrow={true}
        />
        <Card
          description="lkfmdkmsklml"
          nthGroup={1}
          projectName="lkvfvd"
          imageURLs={[
            'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.hlbmcguirefarry.com%2Fwp-content%2Fuploads%2Fsites%2F96%2F2019%2F02%2Fplaceholder-16.9.jpg&f=1&nofb=1',
            'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.migmawei.ca%2Fsystem%2Fwp-content%2Fuploads%2F2017%2F04%2FPlaceholder_16_9-1.png&f=1&nofb=1',
          ]}
        />
        <button onClick={() => signIn('google')}>SIGN IN</button>
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-gray-700 font-sudo-title">
          Create{' '}
          <span className="bg-gradient-to-t from-sudo-gradtext-dark to-sudo-gradtext-light bg-clip-text text-transparent">
            T3
          </span>{' '}
          App
        </h1>
        <p className="text-2xl text-gray-700 font-sudo-body">
          This stack uses:
        </p>
        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
          <TechnologyCard
            name="NextJS"
            description="The React framework for production"
            documentation="https://nextjs.org/"
          />
          <TechnologyCard
            name="TypeScript"
            description="Strongly typed programming language that builds on JavaScript, giving you better tooling at any scale"
            documentation="https://www.typescriptlang.org/"
          />
          <TechnologyCard
            name="TailwindCSS"
            description="Rapidly build modern websites without ever leaving your HTML"
            documentation="https://tailwindcss.com/"
          />
          <TechnologyCard
            name="tRPC"
            description="End-to-end typesafe APIs made easy"
            documentation="https://trpc.io/"
          />
        </div>
        <Count />
        {session.data && <pre>{JSON.stringify(session.data, null, 2)}</pre>}
      </main>
    </>
  );
};

const Count = () => {
  const [count, setCount] = useState(0);

  return (
    <div>
      {count}
      <button onClick={() => setCount((c) => c + 1)}>+ count</button>
    </div>
  );
};

const TechnologyCard = ({
  name,
  description,
  documentation,
}: TechnologyCardProps) => {
  return (
    <section className="flex flex-col justify-center p-6 duration-500 border-2 bg-sudo-grad1 rounded shadow-xl motion-safe:hover:scale-105">
      <h2 className="text-lg font-sudo-title text-sudo-dark-tan">{name}</h2>
      <p className="text-sm font-sudo-body text-sudo-dark-tan">{description}</p>
      <a
        className="mt-3 text-sm underline text-violet-500 decoration-dotted underline-offset-2"
        href={documentation}
        target="_blank"
        rel="noreferrer"
      >
        Documentation
      </a>
    </section>
  );
};

export default Home;
